version: "3.2"

services:
  redis:
    image: redis:latest
    container_name: redis-foodsave
    command: redis-server --requirepass ""
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - "savefood-db:/var/lib/postgresql/data"
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
volumes:
  savefood-db:

